spring:
  profiles:
    active:
      -dev
---
spring:
  profiles: dev #开发环境
  application:
    name: microservice-config-gxy-dev
---
spring:
  profiles: test #开发环境
  application:
    name: microservice-config-gxy-test